version: 2
formats: []

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# python:
#     version: 3.7
#     install:
#         - requirements: docs/requirements.txt

python:
  install:
    - requirements: docs/requirements.txt
